gabymoreno9/alpha-works-website

- css/styles.css
- index.html
> fix(formatting/bugs): cleaned up code and fixed layout

- index.html
> feat(card): added my profile picture and description

- css/styles.css
- index.html
Changes
1. updated the button that now has a transition
2. updated card
3. updated CSS and info
> feat(card)updated my card and button

- Taofeek.html
Created a background color and initialized the page.
> Feat(Client): Create Background Color

- ChrisBreezy.html
- css/styles.css
#Changes
*Added background color to personal page
#Purpose
just added color
> CL-48-background color

- index.html
- izzy/izzy.html
#Changes
1. Create files (html, css, js, and img) for personal page
2. Link button to personal html file
#Purpose
When a user clicks on the button, it will open a new tab to my AW portfolio page
Closes #43
> feat(izzy-btn): link btn to izzy's page

- css/styles.css
#Changes
*Item 1
*Item 2
#Purpose
#Approach
#Learning
Closes #000
> added in the styles

- README.md
#Changes
*Add Linkedin
Closes #59
> feat(Readme):Added Linkedin url

- README.md
#Changes
*Added name and LinkedIn
Closes #62
> Doc(Client): add name and LinkedIn profile

- README.md
#Changes
*Add Linkedin link to readme
Closes #65
> feat(docs): add Linkedin link

- README.md
#Changes
*Item 1
*Item 2
#Purpose
#Approach
#Learning
Closes #000
> Kf 64 added readmeinfo

- README.md
#Changes
*Add the link to my Linkedin page
#Purpose
To give people a link to click on that will direct them to the Linkedin page
> CL-74-added link to README.md

- README.md
#Changes
*Item 1
*Item 2
#Purpose
#Approach
#Learning
Closes #000
> ip-doc-README.md

- README.md
#Changes
*Add full name to README.md file
*Add LinkedIn link to README.md file
#Purpose
To give users the opportunity to connect with us via LinkedIn
#Approach
If a user goes through our personal page and would like to hire or connect with one or all of us, they can find us on LinkedIn.
#Learning
Closes #52
> feat(docs)Inserting full name and LinkedIn into README.md file

- Taofeek/Taofeek.html
- Taofeek/Taofeek.js
#Changes
*Created a Navbar
*Added 
#Purpose
#Approach
This shows an introductory navigation
Closes #104
> Feat(Client):Create Navbar

- css/styles.css
#Changes
removed error on line 345 in styles.css
#Purpose
Error in code was causing all CSS below 345 to not function
#Approach
removes errors
Closes #112
> fixed small error in code

- izzy/izzy.html
#Changes
Add navbar links to personal page
#Purpose
Create navbar
Closes #109
> feat(navbar): add navbar links

- Eddie/Eddie.html
- css/styles.css
#Changes
*Added new logo location to center of site
*Added a header title and blue underline
#Purpose
To complete the header
Closes #114
> feat(header):added new logo location and header

- css/styles.css
- index.html
#Changes
fixed bug on home page card
#Purpose
style
> bug:card fix on home page

- Sonic/sonic.css
- Sonic/sonic.html
- Trish/trish.css
- Trish/trish.html
- Trish/trish.js
- index.html
#Changes
*Made navbar for Trish's page
*Made navbar for Sonic's page
Closes#106
> Tb-106-create-navbar

- Eddie/Eddie.html
- css/styles.css
#Changes
*Fix underline responsiveness
*Fix Logo link not working
#Purpose
So the site can be responsive and the logo clickable to home page.
#Approach
Now the header is good and links click.
Closes #119
> fix(header):Fixed header and logo link

- README.md
#Changes
*Added my linkedIn to readMe file
#Purpose
Added to readMe
#Approach
N/A
#Learning
N/A
Closes #128
> feat(readMe): Added my linkedin to readMe file

- index.html
#Changes
link on card opens personal page onto a separate tab
> feat: button on card opens up a seperate tab

- index.html
#Changes
*Item 1
*Item 2
#Purpose
#Approach
#Learning
Closes #000
> Added Browser Button

- Taofeek/Taofeek.html
- index.html
#Changes
*Added connectivity to card
*Added LinkedIn and Github to page 
#Purpose
Basic connectivity to social accounts 
Closes #146
> Feat(Client):Ensure Basic Connectivity

- css/styles.css
- index.html
#Changes
*Centered name on card
*Centered text on card
#Purpose
#Approach
#Learning
Closes #155
> Jm-155-centername-on-card

- Misael/Misael.html
- Misael/css/misael.css
- Misael/js/misael.js
#Changes
*Added cursor animation
*Added text animation
#Purpose
Added animation that shows text to user
#Approach
Shows user words that describe me
#Learning
I learned about using wait with Promise and async functions. I also learned about setTimeout
[delaying JS]<https://www.sitepoint.com/delay-sleep-pause-wait/>
[wait Mozilla]<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await>
Closes #153
> 153 mb text animation

- css/styles.css
#Changes
*Changed color glow on card hover
*Changed color to purple
*Changed card border to a dark purple to give it more pop
#Purpose
Feature gives the card more of a pop and goes with the color scheme
#Approach
Just makes the card more visually appealing
#Learning
Closes #157
> feat(css) Change color glow on hover

- index.html
#Changes
*New click for new tab added
#Purpose
So the page can click on a new tab when the home button is pushed.
Closes #165
> feat(new tab): Home button clicks to new tab

- index.html
#Changes
Bug fix
#Purpose
Link the homepage to the profile.
Closes #167
> feat(bug fix):fixed the homepage link to profile

- Misael/Misael.html
- Misael/css/misael.css
- Misael/js/misael.js
#Changes
*Add skills list with animation
*Started the about section
*Added CSS styling and modified some existing styles
#Purpose
Added an about section so users can learn about me
#Approach
N/A
#Learning
N/A
Closes #163
> 163 mb about section

- Kenny/Kenny.html
#Changes
*Item 1
*Item 2
#Purpose
#Approach
#Learning
Closes #000
> Created Navbar

- Kenny/Kenny.css
- Kenny/Kenny.html
#Changes
*Item 1
*Item 2
#Purpose
#Approach
#Learning
Closes #000
> Changed Background

- Eddie/Eddie.html
- Eddie/styles.css
#Changes
*Added a footer
*Links
#Purpose
footer with links and contact
Closes #173
> feat(footer):added a footer with links

- Taofeek/Taofeek.css
- Taofeek/Taofeek.html
- Taofeek/Taofeek.js
#Changes
*Added Footer and Toggled it 
*Added animation to the Toggler
Closes #000
> Feat(Client): TA-184-Toggle-Footer

- Eddie/Eddie.html
#Changes
*Social media links
#Purpose
So people can clink on the links to my social media.
Closes #188
> feat(footer links):Added links

- jacky/jacky-personal.html
- jacky/jacky-styles.css
#Changes
*Added a logo
*Added a navbar
#Purpose
A logo for customization and a navbar for navigation within the webpage
#Approach
Logo when clicked will later have the function to take the user back to main class page. The navbar will later be useful to navigate the user through out the webpage using the tabs
#Learning
Navbar used from Bootstrap
Closes #160
> feat(jacky-html-and-css) add a navbar and a logo

- css/styles.css
- dustin/css/dustin-css.css
- dustin/js/dustin-main.js
- index.html
#Changes
Fixes weird animation on button hover
#Purpose
Button hover had placeholder CSS animation
#Approach
Closes #197
> Changed button animation

- css/styles.css
- index.html
- ivan/ivan.css
- ivan/ivan.html
#Changes
Button style changed
about me added
made layout responsive
#Purpose
More commit/PR practice
#Learning
Used media querys
Closes #199
> ip-199-feat-button
